#define MAX_COBRA 100

#define ESQUERDA 82
#define DIREITA 83
#define CIMA 84
#define BAIXO 85
#define ESC 27

#define DESENHAR_PEDACO_COBRA 1
#define APAGAR_PEDACO_COBRA 2
#define DESENHAR_CABECA 3
#define DESENHAR_COBRA_INTEIRA 4
#define APAGAR_COBRA_INTEIRA 5
